### ISSUE TITLE
Great plugin for Grav, thank you!

### ISSUE THREAD

**Issue by paulhibbitts** [orx57/grav-plugin-feed-us#1]
Thanks so much for contributing this Plugin to the Grav community, for myself and many of my fellow educators being able to add an RSS feed to Grav is very useful!

I see that on your roadmap you have this item:
Ability to import multiple feeds

Would that mean you I could have multiple feeds be presented within one list within Grav? If so, that would be a very valuable addition. 

Are you also thinking of adding a few options regarding the display of RSS feed items? For example, something like this?

<RSS Item Link>
Source: Grav Blog | Published on 2016-05-06

Thanks again for this great plugin. If I can be of any help re: testing, etc. please let me know.
Paul

**Comment by orx57** [comment]
Hi @paulhibbitts,
First of all, thank you for your encouragement!

The idea is effectively to be able to display the different feeds into a single list. But I will first implement the option to display multiple feeds independently of each other.

Regarding the display options of the feeds, i already take into account some attributes, but I have not yet fully documented. I'll take soon into account more attributes and document the usage in the twig template.

**Comment by paulhibbitts** [comment]
Thanks very much @orx57, I look forward to the continued development of the plugin!

Cheers,
Paul
