### ISSUE TITLE
Not Working with Google Alert RSS Feed

### ISSUE THREAD

**Issue by briankb** [orx57/grav-plugin-feed-us#2]
I installed the plugin via Admin (GPM) and the default getgrav feed worked and also one from cnet news but not this customized rss feed that was generated by google alert

https://www.google.com/alerts/feeds/17579563393039458159/12905895742934486495

I verified the link is public and accessible. Is it the formatting Google is using?

**Comment by briankb** [comment]
Any idea when you may be able to review and upload a fix for this?

**Comment by orx57** [comment]
Hi @briankb, Thanks for reporting this issue.

The initial version of this plugins only supported RSS type feed.
Your customized feed is an ATOM type feed.

I have added now the ATOM support.
I have succesfully tested your feed and the ATOM type feed of Grav blog (https://getgrav.org/blog.atom).

Should be publish in the next GPM update.
